# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fo-training' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fo-training
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'AlamofireImage', '~> 3.3'
  pod 'IQKeyboardManagerSwift'


end
